### ISSUE TITLE
 the sound extraction from the demo following the CS2 update on May 29th exhibits audible glitches

### ISSUE THREAD

**Issue by Dark11296** [akiver/csgo-voice-extractor#5]
Hello, the sound extraction from the demo following the CS2 update on May 29th exhibits audible glitches, whereas the previous version was functioning correctly. use v2.1.3,Is this issue fixable? Thank you.

**Comment by Dark11296** [comment]
wav [sample.zip](https://github.com/user-attachments/files/15838831/sample.zip)

**Comment by akiver** [comment]
It looks like it was a CS2 issue and it's has been fixed.
I tried with a recent random [faceit match](https://www.faceit.com/en/cs2/room/1-b81721e4-bd93-44e8-8002-ab60bd5e4fdf) and there is no glitch.
